version: "3.4"
services:
  postgres-9_6_6:
    image: "postgres:9.6.6"
    # env_file:
    #   - ./common.env
    # restart: always
    environment:
      - POSTGRES_PASSWORD=${DBA_PASSWORD}
      - POSTGRES_USER=${DBA_USER}
      - POSTGRES_DB=${DBA_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres-9_6_6:/var/lib/postgresql/data"
#      - "postgres-9_6_6"
#volumes:
#  postgres-9_6_6:
